### ISSUE TITLE
que.js not included in npm install

### ISSUE THREAD

**Issue by DerHowie** [radiovisual/npm-install-que#1]
module.js:341
    throw err;
    ^

Error: Cannot find module './que.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm-install-que/index.js:5:11)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)

**Comment by radiovisual** [comment]
oops, que.js needs to be added to the "files" sections of the package.json
